import type { SourceStatus } from "@/features/sources/model/types";

export const demoSources: readonly SourceStatus[] = [
  {
    id: "rwa-fund-factsheet",
    title: "Short-duration tokenized credit fund factsheet",
    kind: "Fund factsheet",
    publishedAt: "2026-08-13T00:00:00.000Z",
    fetchedAt: "2026-08-14T08:58:18.000Z",
    contentHash: `0x${"31".repeat(32)}`,
    stale: false,
    description: "NAV, duration, gross yield, spread, and redemption terms for the RWA sleeve.",
    integration: "fixture",
  },
  {
    id: "private-credit-memo",
    title: "Private-credit monitoring memorandum",
    kind: "Credit memo",
    publishedAt: "2026-08-12T00:00:00.000Z",
    fetchedAt: "2026-08-14T08:58:21.000Z",
    contentHash: `0x${"32".repeat(32)}`,
    stale: false,
    description: "Obligor concentration, advance-rate, servicing, and redemption-risk monitoring.",
    integration: "fixture",
  },
  {
    id: "rate-statement",
    title: "Monetary-policy statement extract",
    kind: "Rate announcement",
    publishedAt: "2026-08-11T00:00:00.000Z",
    fetchedAt: "2026-08-14T08:58:24.000Z",
    contentHash: `0x${"33".repeat(32)}`,
    stale: false,
    description: "Liquid benchmark rates and the changing opportunity cost of credit exposure.",
    integration: "fixture",
  },
  {
    id: "okx-liquidity-snapshot",
    title: "OKX DEX exit-liquidity quote",
    kind: "Liquidity",
    publishedAt: "2026-08-14T08:55:00.000Z",
    fetchedAt: "2026-08-14T08:58:27.000Z",
    contentHash: `0x${"34".repeat(32)}`,
    stale: false,
    description: "Point-in-time route depth, estimated price impact, and exit slippage on X Layer mainnet.",
    integration: "live",
  },
  {
    id: "xlayer-vault-state",
    title: "Vault and adapter state",
    kind: "On-chain state",
    publishedAt: "2026-08-14T09:00:00.000Z",
    fetchedAt: "2026-08-14T09:00:00.000Z",
    contentHash: `0x${"35".repeat(32)}`,
    stale: false,
    description: "Current balances, APYs, policy limits, cooldown, and recent decisions read from X Layer.",
    integration: "chain",
  },
];
